services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always

  flask:
    build: .
    container_name: flask_docker
    expose:
      - 5000
    restart: always